/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.exercicios;

import aritmetica.CalcularMediana;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author COVELO
 */
public class Mediana extends javax.swing.JFrame {
    
    private double mediana;
    private String primeiro_passo;
    private String segundo_passo;
    
    public Mediana() {
        initComponents();
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/view/dashboard/imagens/logo-feea.png"));  
        setIconImage(icon.getImage());
    }
    
    public void EntradaDeDados(String[] valores){
        
        CalcularMediana calcMediana = new CalcularMediana();
        
        calcMediana.EntradaDeDados(valores);
        this.primeiro_passo = calcMediana.PrimeiroPasso();
        this.segundo_passo = calcMediana.SegundoPasso();
        
        this.mediana = calcMediana.getMediana();
        
        txtPrimeiroPasso.setText(this.primeiro_passo);
        txtSegundoPasso.setText(this.segundo_passo);
        lbResposta.setText("A resposta é " + String.valueOf(this.mediana));
        
        MostrarEmTela();
    }
    
    private void MostrarEmTela(){
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBase = new javax.swing.JPanel();
        pnResolucao = new javax.swing.JPanel();
        spResolucao = new javax.swing.JScrollPane();
        pnPassoAPasso = new javax.swing.JPanel();
        pnPasso1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrimeiroPasso = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lbTituloResolucao = new javax.swing.JLabel();
        lbResposta = new javax.swing.JLabel();
        pnPasso2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSegundoPasso = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mediana");
        setBackground(new java.awt.Color(255, 255, 255));

        pnBase.setBackground(new java.awt.Color(255, 255, 255));
        pnBase.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnBase.setMinimumSize(new java.awt.Dimension(1000, 600));

        pnResolucao.setBackground(new java.awt.Color(255, 255, 255));

        spResolucao.setBorder(null);
        spResolucao.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnPassoAPasso.setBackground(new java.awt.Color(255, 255, 255));

        pnPasso1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setText("1º Passo");

        txtPrimeiroPasso.setEditable(false);
        txtPrimeiroPasso.setColumns(20);
        txtPrimeiroPasso.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtPrimeiroPasso.setRows(5);
        jScrollPane1.setViewportView(txtPrimeiroPasso);

        javax.swing.GroupLayout pnPasso1Layout = new javax.swing.GroupLayout(pnPasso1);
        pnPasso1.setLayout(pnPasso1Layout);
        pnPasso1Layout.setHorizontalGroup(
            pnPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPasso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnPasso1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnPasso1Layout.setVerticalGroup(
            pnPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPasso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(93, 188, 210));

        lbTituloResolucao.setBackground(new java.awt.Color(93, 188, 210));
        lbTituloResolucao.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        lbTituloResolucao.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloResolucao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloResolucao.setText("Resolução do Exercício");

        lbResposta.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        lbResposta.setForeground(new java.awt.Color(255, 255, 255));
        lbResposta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloResolucao, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTituloResolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(lbResposta)
                    .addContainerGap(99, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnPassoAPassoLayout = new javax.swing.GroupLayout(pnPassoAPasso);
        pnPassoAPasso.setLayout(pnPassoAPassoLayout);
        pnPassoAPassoLayout.setHorizontalGroup(
            pnPassoAPassoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPasso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnPassoAPassoLayout.setVerticalGroup(
            pnPassoAPassoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPassoAPassoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnPasso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        spResolucao.setViewportView(pnPassoAPasso);

        javax.swing.GroupLayout pnResolucaoLayout = new javax.swing.GroupLayout(pnResolucao);
        pnResolucao.setLayout(pnResolucaoLayout);
        pnResolucaoLayout.setHorizontalGroup(
            pnResolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spResolucao, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnResolucaoLayout.setVerticalGroup(
            pnResolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spResolucao)
        );

        pnPasso2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("2º Passo");

        txtSegundoPasso.setEditable(false);
        txtSegundoPasso.setColumns(20);
        txtSegundoPasso.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtSegundoPasso.setRows(5);
        jScrollPane2.setViewportView(txtSegundoPasso);

        javax.swing.GroupLayout pnPasso2Layout = new javax.swing.GroupLayout(pnPasso2);
        pnPasso2.setLayout(pnPasso2Layout);
        pnPasso2Layout.setHorizontalGroup(
            pnPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPasso2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPasso2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        pnPasso2Layout.setVerticalGroup(
            pnPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPasso2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnBaseLayout = new javax.swing.GroupLayout(pnBase);
        pnBase.setLayout(pnBaseLayout);
        pnBaseLayout.setHorizontalGroup(
            pnBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnResolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPasso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnBaseLayout.setVerticalGroup(
            pnBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBaseLayout.createSequentialGroup()
                .addComponent(pnResolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPasso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mediana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbResposta;
    private javax.swing.JLabel lbTituloResolucao;
    private javax.swing.JPanel pnBase;
    private javax.swing.JPanel pnPasso1;
    private javax.swing.JPanel pnPasso2;
    private javax.swing.JPanel pnPassoAPasso;
    private javax.swing.JPanel pnResolucao;
    private javax.swing.JScrollPane spResolucao;
    private javax.swing.JTextArea txtPrimeiroPasso;
    private javax.swing.JTextArea txtSegundoPasso;
    // End of variables declaration//GEN-END:variables
}
