/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dashboard;

import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import view.exercicios.DistribuicaoFrequencia;
import view.exercicios.Media;
import view.exercicios.Mediana;

/**
 *
 * @author COVELO
 */
public class Home extends javax.swing.JFrame {

    static boolean maximizado = false;
    int xMouse;
    int yMouse;
    
    static boolean btnMediaClicado              = false;
    static boolean btnMedianaClicado            = false;
    static boolean btnModaClicado               = false;
    static boolean btnGrandesConjuntosClicado   = false;
    
    private boolean exercicioMedia      = false;
    private boolean exercicioMediana    = false;
    private boolean exercicioFrequencia = false;
    
    String[] valoresMediana;
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHeader = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        pnNav = new javax.swing.JPanel();
        lbInformativo = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        lbNomeProjeto = new javax.swing.JLabel();
        lbSubtitulo = new javax.swing.JLabel();
        btnMedia = new javax.swing.JButton();
        btnMediana = new javax.swing.JButton();
        btnGrandesConjuntos = new javax.swing.JButton();
        lbMedia = new javax.swing.JLabel();
        lbMediana = new javax.swing.JLabel();
        lbGrandesConjuntos = new javax.swing.JLabel();
        pnTituloDesmonstracao = new javax.swing.JPanel();
        lbDemonstrativo = new javax.swing.JLabel();
        lbNomeExercicioSelecionado = new javax.swing.JLabel();
        pnEntradaDeDados = new javax.swing.JPanel();
        pnMediaMediana = new javax.swing.JPanel();
        lbHeaderMediaMediana = new javax.swing.JLabel();
        pnInputUsuario = new javax.swing.JPanel();
        lbInputMediaMediana = new javax.swing.JLabel();
        inputValoresMediaMediana = new javax.swing.JTextField();
        btnCalcularMediaMediana = new javax.swing.JButton();
        lbInputFrequencia = new javax.swing.JLabel();
        inputValoresFrequencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ferramenta Educacional para Estatística Aplicada | F.E.E.A");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnHeaderMouseDragged(evt);
            }
        });
        pnHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnHeaderMousePressed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard/imagens/Minimize.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.setOpaque(true);
        btnMinimizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard/imagens/Minimize (2).png"))); // NOI18N
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });

        btnFechar.setBackground(new java.awt.Color(255, 255, 255));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard/imagens/Exit.png"))); // NOI18N
        btnFechar.setBorderPainted(false);
        btnFechar.setContentAreaFilled(false);
        btnFechar.setFocusPainted(false);
        btnFechar.setOpaque(true);
        btnFechar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard/imagens/Exit (2).png"))); // NOI18N
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFecharMouseExited(evt);
            }
        });

        btnMaximizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard/imagens/Maximize.png"))); // NOI18N
        btnMaximizar.setBorderPainted(false);
        btnMaximizar.setContentAreaFilled(false);
        btnMaximizar.setFocusPainted(false);
        btnMaximizar.setOpaque(true);
        btnMaximizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard/imagens/Maximize (2).png"))); // NOI18N
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMinimizar)
                .addGap(0, 0, 0)
                .addComponent(btnMaximizar)
                .addGap(0, 0, 0)
                .addComponent(btnFechar)
                .addGap(0, 0, 0))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimizar)
            .addComponent(btnFechar)
            .addComponent(btnMaximizar)
        );

        pnNav.setBackground(new java.awt.Color(255, 255, 255));

        lbInformativo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbInformativo.setForeground(new java.awt.Color(52, 152, 219));
        lbInformativo.setText("Você está na área do aluno.");

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard/imagens/logo-feea.png"))); // NOI18N

        lbNomeProjeto.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        lbNomeProjeto.setText("Ferramenta Educacional para Estatística Aplicada");

        lbSubtitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSubtitulo.setForeground(new java.awt.Color(52, 152, 219));
        lbSubtitulo.setText("Escolha um dos exercícios abaixo");

        btnMedia.setBackground(new java.awt.Color(255, 255, 255));
        btnMedia.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnMedia.setText("Média");
        btnMedia.setBorder(null);
        btnMedia.setBorderPainted(false);
        btnMedia.setContentAreaFilled(false);
        btnMedia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedia.setFocusPainted(false);
        btnMedia.setMaximumSize(new java.awt.Dimension(85, 25));
        btnMedia.setMinimumSize(new java.awt.Dimension(85, 25));
        btnMedia.setOpaque(true);
        btnMedia.setPreferredSize(new java.awt.Dimension(85, 25));
        btnMedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMediaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMediaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMediaMouseExited(evt);
            }
        });

        btnMediana.setBackground(new java.awt.Color(255, 255, 255));
        btnMediana.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnMediana.setText("Mediana");
        btnMediana.setBorder(null);
        btnMediana.setBorderPainted(false);
        btnMediana.setContentAreaFilled(false);
        btnMediana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMediana.setFocusPainted(false);
        btnMediana.setMaximumSize(new java.awt.Dimension(85, 25));
        btnMediana.setMinimumSize(new java.awt.Dimension(85, 25));
        btnMediana.setOpaque(true);
        btnMediana.setPreferredSize(new java.awt.Dimension(85, 25));
        btnMediana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedianaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMedianaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMedianaMouseExited(evt);
            }
        });

        btnGrandesConjuntos.setBackground(new java.awt.Color(255, 255, 255));
        btnGrandesConjuntos.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnGrandesConjuntos.setText("Distribuição de Frequência");
        btnGrandesConjuntos.setBorder(null);
        btnGrandesConjuntos.setBorderPainted(false);
        btnGrandesConjuntos.setContentAreaFilled(false);
        btnGrandesConjuntos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrandesConjuntos.setFocusPainted(false);
        btnGrandesConjuntos.setOpaque(true);
        btnGrandesConjuntos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrandesConjuntosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGrandesConjuntosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGrandesConjuntosMouseExited(evt);
            }
        });

        lbMedia.setBackground(new java.awt.Color(255, 255, 255));
        lbMedia.setOpaque(true);

        lbMediana.setBackground(new java.awt.Color(255, 255, 255));
        lbMediana.setOpaque(true);

        lbGrandesConjuntos.setBackground(new java.awt.Color(255, 255, 255));
        lbGrandesConjuntos.setOpaque(true);

        javax.swing.GroupLayout pnNavLayout = new javax.swing.GroupLayout(pnNav);
        pnNav.setLayout(pnNavLayout);
        pnNavLayout.setHorizontalGroup(
            pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNavLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbLogo)
                .addGap(18, 18, 18)
                .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNavLayout.createSequentialGroup()
                        .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbSubtitulo)
                            .addGroup(pnNavLayout.createSequentialGroup()
                                .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGrandesConjuntos)
                                    .addComponent(lbGrandesConjuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbNomeProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(314, Short.MAX_VALUE))
                    .addGroup(pnNavLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbInformativo)
                        .addGap(10, 10, 10))))
        );
        pnNavLayout.setVerticalGroup(
            pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnNavLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNavLayout.createSequentialGroup()
                        .addComponent(lbInformativo)
                        .addGap(37, 37, 37)
                        .addComponent(lbNomeProjeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSubtitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbGrandesConjuntos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNavLayout.createSequentialGroup()
                                .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMedia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnGrandesConjuntos)
                                        .addComponent(btnMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnNavLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbMedia, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE))
                                    .addGroup(pnNavLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lbMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
        );

        pnTituloDesmonstracao.setBackground(new java.awt.Color(93, 188, 210));

        lbDemonstrativo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbDemonstrativo.setForeground(new java.awt.Color(255, 255, 255));
        lbDemonstrativo.setText("Demonstrativo do exercício");

        lbNomeExercicioSelecionado.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbNomeExercicioSelecionado.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnTituloDesmonstracaoLayout = new javax.swing.GroupLayout(pnTituloDesmonstracao);
        pnTituloDesmonstracao.setLayout(pnTituloDesmonstracaoLayout);
        pnTituloDesmonstracaoLayout.setHorizontalGroup(
            pnTituloDesmonstracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloDesmonstracaoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbDemonstrativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNomeExercicioSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTituloDesmonstracaoLayout.setVerticalGroup(
            pnTituloDesmonstracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTituloDesmonstracaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTituloDesmonstracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNomeExercicioSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDemonstrativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnEntradaDeDados.setBackground(new java.awt.Color(255, 255, 255));

        pnMediaMediana.setBackground(new java.awt.Color(255, 250, 240));
        pnMediaMediana.setMaximumSize(new java.awt.Dimension(600, 327));
        pnMediaMediana.setMinimumSize(new java.awt.Dimension(600, 327));
        pnMediaMediana.setPreferredSize(new java.awt.Dimension(600, 327));
        pnMediaMediana.setVisible(false);

        lbHeaderMediaMediana.setBackground(new java.awt.Color(93, 188, 210));
        lbHeaderMediaMediana.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lbHeaderMediaMediana.setForeground(new java.awt.Color(255, 255, 255));
        lbHeaderMediaMediana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeaderMediaMediana.setText("Entre com os dados para visulizar a resolução do exercício");
        lbHeaderMediaMediana.setOpaque(true);

        pnInputUsuario.setBackground(new java.awt.Color(255, 250, 240));

        lbInputMediaMediana.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lbInputMediaMediana.setText("Informe os números separando por \";\" (ponto e vírgula):");

        inputValoresMediaMediana.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        btnCalcularMediaMediana.setBackground(new java.awt.Color(93, 188, 210));
        btnCalcularMediaMediana.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        btnCalcularMediaMediana.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularMediaMediana.setText("Mostrar Resolução");
        btnCalcularMediaMediana.setBorder(null);
        btnCalcularMediaMediana.setBorderPainted(false);
        btnCalcularMediaMediana.setFocusPainted(false);
        btnCalcularMediaMediana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMediaMedianaMouseClicked(evt);
            }
        });
        btnCalcularMediaMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularMediaMedianaActionPerformed(evt);
            }
        });

        lbInputFrequencia.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lbInputFrequencia.setText("Informe a frêquencia separando por \";\" (ponto e vírgula):");

        inputValoresFrequencia.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnInputUsuarioLayout = new javax.swing.GroupLayout(pnInputUsuario);
        pnInputUsuario.setLayout(pnInputUsuarioLayout);
        pnInputUsuarioLayout.setHorizontalGroup(
            pnInputUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInputUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInputUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputValoresMediaMediana)
                    .addComponent(btnCalcularMediaMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputValoresFrequencia)
                    .addGroup(pnInputUsuarioLayout.createSequentialGroup()
                        .addGroup(pnInputUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbInputMediaMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbInputFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnInputUsuarioLayout.setVerticalGroup(
            pnInputUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInputUsuarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbInputMediaMediana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputValoresMediaMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbInputFrequencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputValoresFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnCalcularMediaMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnMediaMedianaLayout = new javax.swing.GroupLayout(pnMediaMediana);
        pnMediaMediana.setLayout(pnMediaMedianaLayout);
        pnMediaMedianaLayout.setHorizontalGroup(
            pnMediaMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHeaderMediaMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMediaMedianaLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(pnInputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        pnMediaMedianaLayout.setVerticalGroup(
            pnMediaMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMediaMedianaLayout.createSequentialGroup()
                .addComponent(lbHeaderMediaMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnInputUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnEntradaDeDadosLayout = new javax.swing.GroupLayout(pnEntradaDeDados);
        pnEntradaDeDados.setLayout(pnEntradaDeDadosLayout);
        pnEntradaDeDadosLayout.setHorizontalGroup(
            pnEntradaDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEntradaDeDadosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnMediaMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnEntradaDeDadosLayout.setVerticalGroup(
            pnEntradaDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEntradaDeDadosLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(pnMediaMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnEntradaDeDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTituloDesmonstracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnTituloDesmonstracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnEntradaDeDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1000, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseEntered
        
        // Color devo fornecer uma cor no formato RGB
        btnFechar.setBackground(new Color(232,17,35));
        
    }//GEN-LAST:event_btnFecharMouseEntered

    private void btnFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseExited
        
        // Color devo fornecer uma cor no formato RGB
        btnFechar.setBackground(new Color(255,255,255));
        
    }//GEN-LAST:event_btnFecharMouseExited

    private void btnMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseEntered
        
        // Color devo fornecer uma cor no formato RGB
        btnMaximizar.setBackground(new Color(229,229,229));
        
    }//GEN-LAST:event_btnMaximizarMouseEntered

    private void btnMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseExited
        
        // Color devo fornecer uma cor no formato RGB
        btnMaximizar.setBackground(new Color(255,255,255));
        
    }//GEN-LAST:event_btnMaximizarMouseExited

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        
        // Color devo fornecer uma cor no formato RGB
        btnMinimizar.setBackground(new Color(229,229,229));
        
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        
        // Color devo fornecer uma cor no formato RGB
        btnMinimizar.setBackground(new Color(255,255,255));
        
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked
        
        System.exit(0);
        
    }//GEN-LAST:event_btnFecharMouseClicked

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        
        if(maximizado){
            Home.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            Home.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximizado = false;
        }else{
            setExtendedState(JFrame.NORMAL);
            maximizado = true;
        }
        
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        
        this.setState(Frame.ICONIFIED);
        
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void pnHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHeaderMousePressed
        
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_pnHeaderMousePressed

    private void pnHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHeaderMouseDragged
        
        if(maximizado){
            
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            
            this.setLocation(x - xMouse, y - yMouse);
            
        }
        
    }//GEN-LAST:event_pnHeaderMouseDragged

    private void btnMediaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMediaMouseEntered
        lbMedia.setBackground(new Color(93,188,210));
    }//GEN-LAST:event_btnMediaMouseEntered

    private void btnMediaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMediaMouseExited
        
        if(!btnMediaClicado){
            lbMedia.setBackground(new Color(255,255,255));
        }
        
    }//GEN-LAST:event_btnMediaMouseExited

    private void btnMediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMediaMouseClicked
        
        inputValoresMediaMediana.setText("70;50;60;80");
        
        lbInputMediaMediana.setText("Informe os valores separando por ';' (ponto e vírgula):");
        inputValoresFrequencia.setVisible(true);
        
        lbInputFrequencia.setVisible(false);
        inputValoresFrequencia.setVisible(false);
        
        exercicioMedia      = true;
        exercicioMediana    = false;
        exercicioFrequencia = false;
        
        lbMediana.setBackground(new Color(255,255,255));
        lbGrandesConjuntos.setBackground(new Color(255,255,255));
        
        btnMedianaClicado = false;
        btnModaClicado = false;
        btnGrandesConjuntosClicado = false;
        
        if(btnMediaClicado == false){
            
            lbMedia.setBackground(new Color(93,188,210));
            lbNomeExercicioSelecionado.setText("Média.");
            btnMediaClicado = true;
            
            pnMediaMediana.setVisible(true);

        }else{
            
            lbMedia.setBackground(new Color(255,255,255));
            lbNomeExercicioSelecionado.setText("");
            btnMediaClicado = false;
            
            pnMediaMediana.setVisible(false);
            
        }
        
    }//GEN-LAST:event_btnMediaMouseClicked

    private void btnMedianaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedianaMouseClicked
        
        inputValoresMediaMediana.setText("10;20;5;15;30;45");
        
        lbInputMediaMediana.setText("Informe os valores separando por ';' (ponto e vírgula):");
        inputValoresFrequencia.setVisible(true);
        
        lbInputFrequencia.setVisible(false);
        inputValoresFrequencia.setVisible(false);
        
        exercicioMedia      = false;
        exercicioMediana    = true;
        exercicioFrequencia = false;
        
        lbMedia.setBackground(new Color(255,255,255));
        lbGrandesConjuntos.setBackground(new Color(255,255,255));
        
        btnMediaClicado = false;
        btnGrandesConjuntosClicado = false;
        
        if(btnMedianaClicado == false){
            
            lbMediana.setBackground(new Color(93,188,210));
            lbNomeExercicioSelecionado.setText("Mediana.");
            btnMedianaClicado = true;
            
            pnMediaMediana.setVisible(true);
            
        }else{
            
            lbMediana.setBackground(new Color(255,255,255));
            lbNomeExercicioSelecionado.setText("");
            btnMedianaClicado = false;
            
            pnMediaMediana.setVisible(false);
            
        }
        
    }//GEN-LAST:event_btnMedianaMouseClicked

    private void btnMedianaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedianaMouseEntered
        lbMediana.setBackground(new Color(93,188,210));
    }//GEN-LAST:event_btnMedianaMouseEntered

    private void btnMedianaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedianaMouseExited
        
        if(!btnMedianaClicado){
            lbMediana.setBackground(new Color(255,255,255));
        }
        
    }//GEN-LAST:event_btnMedianaMouseExited

    private void btnGrandesConjuntosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrandesConjuntosMouseClicked
        
        inputValoresMediaMediana.setText("100-200;200-300;300-400;400-500;500-600");
        inputValoresFrequencia.setText("5;10;2;1;15");
        
        lbInputMediaMediana.setText("Informe o intervalo separando por ';' (ponto e vírgula):");
        inputValoresMediaMediana.setToolTipText("Ex: 100-200;200-300;300-400");
        inputValoresMediaMediana.setVisible(true);
        
        lbInputFrequencia.setVisible(true);
        inputValoresFrequencia.setVisible(true);
        
        lbMedia.setBackground(new Color(255,255,255));
        lbMediana.setBackground(new Color(255,255,255));
        
        btnMediaClicado = false;
        btnMedianaClicado = false;
        btnModaClicado = false;
        
        exercicioMedia      = false;
        exercicioMediana    = false;
        exercicioFrequencia = true;
        
        if(!btnGrandesConjuntosClicado){
            
            lbGrandesConjuntos.setBackground(new Color(93,188,210));
            lbNomeExercicioSelecionado.setText("Distribuição de Frequência.");
            btnGrandesConjuntosClicado = true;
            
            pnMediaMediana.setVisible(true);
            
        }else{
            lbGrandesConjuntos.setBackground(new Color(255,255,255));
            btnGrandesConjuntosClicado = false;
            
            pnMediaMediana.setVisible(false);
            
        }
        
    }//GEN-LAST:event_btnGrandesConjuntosMouseClicked

    private void btnGrandesConjuntosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrandesConjuntosMouseEntered
        lbGrandesConjuntos.setBackground(new Color(93,188,210));
    }//GEN-LAST:event_btnGrandesConjuntosMouseEntered

    private void btnGrandesConjuntosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrandesConjuntosMouseExited
        
        if(!btnGrandesConjuntosClicado){
            lbGrandesConjuntos.setBackground(new Color(255,255,255));
        }
        
    }//GEN-LAST:event_btnGrandesConjuntosMouseExited

    private void btnCalcularMediaMedianaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMediaMedianaMouseClicked
        
        String[] dados = null;
        String[] intervalos = null;
        String[] frequencia = null;
        boolean startarTela = false;
        
        if(exercicioMedia == true || exercicioMediana == true){
            
            try {
            
                dados = inputValoresMediaMediana.getText().split(";");
            
                if(dados.length==1){
                    JOptionPane.showMessageDialog(
                        this, 
                        "É necessário informar mais de um número."
                    );
                }else{
                    startarTela = true;
                }
            
            }catch (Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
          
        if(exercicioMedia == true && startarTela == true){
        
            Media vMedia = new Media();

            vMedia.EntradaDeDados(dados);
            //vMedia.setExtendedState(JFrame.MAXIMIZED_BOTH);
            vMedia.setResizable(false);
            vMedia.setLocationRelativeTo(this);
            vMedia.setVisible(true);
            
        }else if(exercicioMediana == true && startarTela == true){
            
            Mediana vMediana = new Mediana();

            vMediana.EntradaDeDados(dados);
            //vMediana.setExtendedState(JFrame.MAXIMIZED_BOTH);
            vMediana.setResizable(false);
            vMediana.setLocationRelativeTo(this);
            vMediana.setVisible(true);
            
        }else if(exercicioFrequencia == true){
            
            intervalos = inputValoresMediaMediana.getText().split(";");
            frequencia = inputValoresFrequencia.getText().split(";");
            
            DistribuicaoFrequencia vDistFrequencia = new DistribuicaoFrequencia();
            vDistFrequencia.EntradaDeDados(intervalos, frequencia);
            vDistFrequencia.setLocationRelativeTo(this);
            vDistFrequencia.setResizable(false);
            vDistFrequencia.setVisible(true);
            
        }
        
    }//GEN-LAST:event_btnCalcularMediaMedianaMouseClicked

    private void btnCalcularMediaMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularMediaMedianaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularMediaMedianaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularMediaMediana;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGrandesConjuntos;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnMedia;
    private javax.swing.JButton btnMediana;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JTextField inputValoresFrequencia;
    private javax.swing.JTextField inputValoresMediaMediana;
    private javax.swing.JLabel lbDemonstrativo;
    private javax.swing.JLabel lbGrandesConjuntos;
    private javax.swing.JLabel lbHeaderMediaMediana;
    private javax.swing.JLabel lbInformativo;
    private javax.swing.JLabel lbInputFrequencia;
    private javax.swing.JLabel lbInputMediaMediana;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMedia;
    private javax.swing.JLabel lbMediana;
    private javax.swing.JLabel lbNomeExercicioSelecionado;
    private javax.swing.JLabel lbNomeProjeto;
    private javax.swing.JLabel lbSubtitulo;
    private javax.swing.JPanel pnEntradaDeDados;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnInputUsuario;
    private javax.swing.JPanel pnMediaMediana;
    private javax.swing.JPanel pnNav;
    private javax.swing.JPanel pnTituloDesmonstracao;
    // End of variables declaration//GEN-END:variables
}
